server:
  servlet:
    context-path: /los/api
  error:
    include-message: always

spring:
  application:
    name: Loan Origination System Regular Mini Version
  profiles:
    active: dev

auth:
  secret-key: WzatJDgR0eBv2Tv48zk2bmuuU7/XEBvIAxZc7fetr74=
  access-token:
   expiration: 60_000 # a minute

