spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/los_regular_mini
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20_000
      max-lifetime: 90_000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 30_000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2KB